CREATE TABLE IF NOT EXISTS player_bills(
    id INT AUTO_INCREMENT PRIMARY KEY,
    citizenid VARCHAR(11) NOT NULL,
    title VARCHAR(255) NOT NULL,
    quantity INT DEFAULT 1,
    paid BOOLEAN DEFAULT FALSE,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);